---
# - hosts: localhost
  # connection: local 
  # become: true
  # become_user: vagrant
  # tasks:
    # - name: Package war file
      # command: 'mvn clean package'
    
- hosts: web
  become: true
  vars:
  - warName: DemoApp.war
  - warRemotePath: /usr/share/tomcat
  - tomcat_ver: 9.0.30                          # Tomcat version to install
  - ui_manager_user: manager                    # User who can access the UI manager section only
  - ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
  - ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
  - ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  tasks:
    - name: include java
      include_role:
        name: geerlingguy.java
    - name: include tomcat
      include_role:
        name: tomcat
    - name: Creates directory
      file:
        path: '{{ warRemotePath }}/DemoApp'
        state: directory
    - name: Delete remote war file
      file: path={{ warRemotePath }}/{{ warName }} state=absent
    - name: Copy WAR to server
      copy:
        src: './target/demo-0.0.1-SNAPSHOT.war'
        dest: '{{ warRemotePath }}/{{ warName }}'
    - name: Unzip WAR file
      unarchive: src='{{ warRemotePath }}/{{ warName }}' dest='{{ warRemotePath }}/DemoApp' copy=no mode=0755 owner=tomcat group=tomcat
      notify:
        - restart tomcat
  handlers:
  - name: restart tomcat
    service: name=tomcat state=restarted